name: flutter_vlc_player
description: A VLC-powered alternative to Flutter's video_player. Supports multiple players on one screen.
version: 6.0.3
homepage: https://github.com/solid-software/flutter_vlc_player/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

flutter:
  plugin:
    platforms:
      android:
        package: software.solid.fluttervlcplayer
        pluginClass: FlutterVlcPlayerPlugin
      ios:
        pluginClass: FlutterVlcPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
 
  meta: ^1.3.0
  pedantic: ^1.11.0
  #flutter_vlc_player_platform_interface: ^1.0.6
  flutter_vlc_player_platform_interface:
    path: ../flutter_vlc_player_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^0.2.1
  plugin_platform_interface: ^2.0.0
